<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bluestaq-api-development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BlueStaq.Application/BlueStaq.Application.csproj" />
    <ProjectReference Include="../BlueStaq.Infrastructure/BlueStaq.Infrastructure.csproj" />
  </ItemGroup>
</Project>

